#!/bin/sh

code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension ask-toolkit.alexa-skills-kit-toolkit
code --install-extension blackmist.LinkCheckMD
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension docsmsft.docs-article-templates
code --install-extension docsmsft.docs-authoring-pack
code --install-extension docsmsft.docs-build
code --install-extension docsmsft.docs-images
code --install-extension docsmsft.docs-linting
code --install-extension docsmsft.docs-markdown
code --install-extension docsmsft.docs-metadata
code --install-extension docsmsft.docs-preview
code --install-extension docsmsft.docs-scaffolding
code --install-extension docsmsft.docs-yaml
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension firsttris.vscode-jest-runner
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.remotehub
code --install-extension GitHub.vscode-pull-request-github
code --install-extension hashicorp.terraform
code --install-extension mindaro-dev.file-downloader
code --install-extension mindaro.mindaro
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-ossdata.vscode-postgresql
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.js-debug-nightly
code --install-extension ms-vscode.live-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension nrwl.angular-console
code --install-extension redhat.vscode-yaml
code --install-extension streetsidesoftware.code-spell-checker
